name: Auto Tag

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get version from Cargo.toml
        id: get_version
        run: |
          VERSION=$(grep -m1 'version =' Cargo.toml | cut -d '"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version found: $VERSION"
      
      - name: Check if tag exists
        id: check_tag
        run: |
          if git tag -l "v$VERSION" | grep -q "v$VERSION"; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
            echo "Tag v$VERSION already exists"
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
            echo "Tag v$VERSION does not exist"
          fi
      
      - name: Create new tag
        if: env.TAG_EXISTS == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"
          echo "Created and pushed tag v$VERSION"