name: Code Coverage

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    coverage:
        name: Coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Rust Cache
              uses: Swatinem/rust-cache@v2

            - name: Install tarpaulin
              run: cargo install cargo-tarpaulin

            - name: Run cargo tarpaulin
              run: cargo tarpaulin --out Xml

            - name: Upload to codecov.io
              uses: codecov/codecov-action@v3
