name: Docs

on:
    push:
        branches: [main]

jobs:
    docs:
        name: Generate Documentation
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Rust Cache
              uses: Swatinem/rust-cache@v2

            - name: Generate docs
              run: cargo doc --no-deps

            - name: Deploy docs to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./target/doc
